services:
    db:
        image: postgres:17
        restart: always
        volumes:
            - db_vol:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            PGUSER: postgres # we need this also since pg_isready relies it
            POSTGRES_DB: strecklistan
            POSTGRES_PASSWORD: password
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "strecklistan"]
            interval: 1s
            timeout: 60s
            retries: 60
            start_period: 80s

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

    frontend:
        build:
            context: .
            dockerfile: docker/dev.frontend.Dockerfile
        volumes:
            - .:/app
            - build_vol:/out
        environment:
            CARGO_BUILD_TARGET_DIR: "/out/target"
        entrypoint: ["trunk", "serve", "--config", "docker.Trunk.toml"]
        links:
            - backend
        ports:
            - 8080:8080

    backend:
        depends_on:
            db:
                condition: service_healthy
                restart: true
        build:
            context: .
            dockerfile: docker/dev.backend.Dockerfile
        volumes:
            - .:/app
            - build_vol:/out
        links:
            - db
        environment:
            CARGO_BUILD_TARGET_DIR: "/out/target"
            DATABASE_URL: "postgres://postgres:password@db/strecklistan"
            RUN_MIGRATIONS: "true"
            ENABLE_STATIC_FILE_CACHE: "false"
            ROCKET_ADDRESS: 0.0.0.0
            ROCKET_PORT: 8000

volumes:
    build_vol: {}
    db_vol: {}
